[package]
name = "dug"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "*"
clap = { version = "4", features = ["derive"] }
futures-util = "0.3"
itertools = "0.10"
prettytable-rs = "0.10"
tokio = { version = "1", features = ["macros", "process", "rt"] }
trust-dns-resolver = { version = "*", features = ["dns-over-rustls"] }
